
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uffwhbexibupaqyjvjrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmZndoYmV4aWJ1cGFxeWp2anJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MjI1ODQsImV4cCI6MjA2MDM5ODU4NH0.pH_ZUgFj9tpemkBxjUutqDPp665WZg5SgR_C0gW5d0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Check connection on load
console.log('Initializing Supabase client with URL:', SUPABASE_URL);
